# Worlds the plugin will be active in
worlds:
- world

# Radius that zombies will follow and aggro
aggro_radius: 160

# Allow zombies to bridge/pillar to reach players
construction: true

# Aggroed zombies will destroy torches they walk by
torch_destruction: true

# Zombies will go out of their way to seek torches on the way to players
torch_seeking: true

# Add more zombies near players instead of relying on vanilla spawning
spawning: true

# Hard cap for zombie spawning. No more will spawn if the living entity populaton is greater or equal to this
spawning_cap: 3000

# How often (in ticks) the horde spawner should run
spawning_frequency: 100

# The maximum number of attempts the spawner will make per player per run
spawning_attempts: 5

# Maximum light level for zombies to spawn (0-16)
spawning_light: 7

# Distance from the player that new zombies should spawn
spawning_radius_max: 80
spawning_radius_min: 24

# Blocks zombies can break, and the number of seconds to do so.
# Set to "[]" to disable completely.
breakable_materials:
  DIRT: 10
  THIN_GLASS: 15
  STONE: 45
