# Worlds the plugin will be active in
worlds:
- world

# Radius that zombies will follow and aggro
aggro_radius: 160

# Speed adult zombies move at. Vanilla is 0.23, which works out to 9.9m/s
adult_zombie_speed: 0.23

# Allow zombies to bridge/pillar to reach players
construction: true

# Aggroed zombies will destroy torches they walk by
torch_destruction: true

# Zombies will go out of their way to seek torches on the way to players
torch_seeking: true

# Add more zombies near players instead of relying on vanilla spawning
spawning: true

# Hard cap for zombie spawning. No more will spawn if the living entity populaton is greater or equal to this
spawning_cap: 3000

# Hard cap for the zombie population immediately surrounding a player. Based on spawning_radius_max.
spawning_nearby_cap: 30

# How often (in ticks) the horde spawner should run
spawning_frequency: 100

# The maximum number of attempts the spawner will make per player per run
spawning_attempts: 10

# Maximum light level for zombies to spawn (0-16)
spawning_light: 7

# Distance from the player that new zombies should spawn
spawning_radius_max: 80
spawning_radius_min: 24

# WHen enabled, zombies place TNT instead of breaking walls
tnt_mode: false

# Blocks zombies can break, and the number of seconds to do so.
# Set to "[]" to disable completely.
breakable_materials:
  DIRT: 10
  SNOW: 30
  CLAY: 30
  BRICK: 90
  GRASS: 30
  WOOD: 30
  LOG: 60
  WORKBENCH: 60
  WOOL: 30
  WOODEN_DOOR: 30
  GLASS: 15
  THIN_GLASS: 15
  WOOD_DOOR: 30
  IRON_DOOR: 90
  LEAVES: 2
  SAND: 30
  OBSIDIAN: 240
  PUMPKIN: 30
  WOOD_STAIRS: 30
  COBBLESTONE_STAIRS: 60
  BRICK_STAIRS: 60
  SMOOTH_STAIRS: 60
  SMOOTH_BRICK: 60
  CHEST: 30
  FURNACE: 60
  COBBLESTONE: 60
  STONE: 45
  GRAVEL: 30
  IRON_ORE: 60
  GOLD_ORE: 60
  COAL_ORE: 60
  IRON_BLOCK: 180
  GOLD_BLOCK: 120
  DIAMOND_BLOCK: 240
  LAPIS_BLOCK: 90
  LAPIS_ORE: 60
  ICE: 15
  STEP: 60
  DOUBLE_STEP: 60
  GLOWSTONE: 30
  FENCE: 60
  IRON_FENCE: 120
  FENCE_GATE: 30
  NETHER_BRICK: 60
  NETHER_FENCE: 60
  NETHER_BRICK_STAIRS: 60
  NETHERRACK: 60
  HUGE_MUSHROOM_1: 30
  HUGE_MUSHROOM_2: 30
  MELON_BLOCK: 15
  CACTUS: 15
  LADDER: 15
  TRAP_DOOR: 30
  JUKEBOX: 30
  TOUCH: 1
